# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB db_entry_ventures
ENV POSTGRES_USER user_entry_ventures
ENV POSTGRES_PASSWORD password_entry_ventures

# Expose the default PostgreSQL port (5432)
EXPOSE 5432